name: whatsapp_ui
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  # Firebase
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  flutter_screenutil: ^5.8.4
  country_picker: ^2.0.20
  cloud_firestore: ^4.8.3
  top_snackbar_flutter: ^3.1.0
  flutter_riverpod: ^2.3.6
  image_picker: ^1.0.1
  firebase_storage: ^11.2.5
  
  flutter_contacts: ^1.1.7
  uuid: ^3.0.7
  intl: ^0.18.1
  video_player: ^2.7.0
  cached_network_image: ^3.2.3
  emoji_picker_flutter: ^1.6.1
  enough_giphy_flutter: ^0.4.0
  flutter_sound: ^9.2.13
  permission_handler: ^10.4.3
  audioplayers: ^5.0.0
  swipe_to: ^1.0.2
  story_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/img/
